name: PortalNetwork
version: 1.3.0-dev
main: au.com.grieve.portalnetwork.PortalNetwork
api-version: "1.13"
authors: [Bundabrg]
description: Allow one to create portals that can easily be linked to each other using colors.
permissions:
  portalnetwork.admin:
    default: op
